### ISSUE TITLE
Crash when trying to generate a tree in the Aether

### ISSUE THREAD

**Issue by BBoldt** [MinecraftModArchive/Dendrology#28] opened 2015-03-09 23:40 UTC
* Forge{10.13.2.1291}
* aether{Alpha 1.7.10-1.2}
* koresample{1.7.10-1.2.5}
* dendrology{1.7.10-1.2.4}
* gilded-games-util{1.7.10-1.1}

I have my config set up like this:
    worldgen {
        # How often ancient trees are found growing in the overworld. 0 disables. Higher values are less rare. [range: 0 ~ 10000, default: 1]
        I:overworldTreeGenRarity=10
    }

http://pastebin.com/NPc6Ygwt

**Comment by BBoldt** [comment] 2015-03-10 00:07
May I suggest a configurable dimension or biome blacklist/whitelist to avoid any other potential issues like this?

**Comment by ScottKillen** [comment] 2015-03-10 03:59
the problem is that aether sets world height to 0 almost everywhere...and I should have checked for that. :wink:

**Comment by ScottKillen** [comment] 2015-03-10 04:03
Fixed in d7013d93b3b8bffd0a66e6492c1647420309a02f

**Closed by ScottKillen** 2015-03-10 04:03 UTC
Labels: Priority: High, Type: Bug
